version: "3.8"

services:
  postgres:
    build:
      context: infra/postgres
      dockerfile: Dockerfile
    container_name: cema_his_postgres
    environment:
      POSTGRES_DB: db_postgres
      POSTGRES_USER: user_postgres
      POSTGRES_PASSWORD: password_postgres
    ports:
      - "5434:5432"
    networks:
      - cema_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user_postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # nuxt:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: cema_his_nuxt
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     NODE_ENV: production
  #     DATABASE_URL: "postgresql://user_postgres:password_postgres@postgres:5432/db_postgres"
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #   networks:
  #     - cema_network

networks:
  cema_network: {}
