version: "3.8"

services:
  postgres:
    build:
      context: infra/postgres
      dockerfile: Dockerfile
    container_name: cema_his_postgres
    environment:
      POSTGRES_DB: db_postgres
      POSTGRES_USER: user_postgres
      POSTGRES_PASSWORD: password_postgres
    ports:
      - "5434:5432"
    # volumes:
    #   - postgres-data:/var/lib/postgresql/data
    networks:
      - cema_network

networks:
  cema_network: {}

# volumes:
#   postgres-data:
#     driver: local
#     driver_opts:
#       type: none
#       o: bind
#       device: ./infra/postgres/data