version: "3.8"

services:
  postgres:
    build:
      context: infra/postgres
      dockerfile: Dockerfile
    container_name: cema_his_postgres
    environment:
      POSTGRES_DB: db_postgres
      POSTGRES_USER: user_postgres
      POSTGRES_PASSWORD: password_postgres
    ports:
      - "5434:5432"
    networks:
      - cema_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user_postgres -d db_postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  cema_network: {}